---
title: "D3vis01"
author: "Mino"
date: "Friday, January 23, 2015"
output:
  html_document:
    highlight: tango
---

# HTML의 기본 형식

HTML 파일과 d3.min.js 파일을 같은 폴더에 두고 크롬에서 실행

배경에서 마우스 오른쪽 클릭 -> "요소 검사" -> 콘솔 창에서 

"d3." 까지 타이핑한 다음에 뭔가 함수목록이 뜬다면 제대로 불러온 것

```html
<!DOCTYPE html>
<html>
  <head>
    <title>D3 first tutorial</title>
    <script type="text/javascript" src="d3.min.js"></script>
  </head>
  <body>
  </body>
</html>

```

# 그림을 그리기 위한 기본 세팅

`<SVG></SVG>` 사이에 원하는 그림을 넣을 것이다
그림을 그릴 수 있는 영역을 지정해줘야함

```html
<!DOCTYPE html>
<html>
  <head>
    <title>D3 first tutorial</title>
    <script type="text/javascript" src="d3.min.js"></script>
  </head>
  <body>
  <svg width = "400", height = "400">
	</svg>
  </body>
</html>
```

크롬 개발자 도구의 Elements 항목에서 `<svg></svg>` 사이에 마우스를 올리면 해당 범위가 어디인지 표시된다

# 사각형 그리기

```html
<!DOCTYPE html>
<html>
  <head>
    <title>D3 first tutorial</title>
    <script type="text/javascript" src="d3.min.js"></script>
  </head>
  <body>
  	<svg width = "400", height = "400">
		<rect width="40", height="40", fill="steelblue"></rect>
	</svg>
  </body>
</html>
```

# 사각형 여러개 그리기

```html
<!DOCTYPE html>
<html>
  <head>
    <title>D3 first tutorial</title>
    <script type="text/javascript" src="d3.min.js"></script>
  </head>
  <body>
  	<svg width = "400", height = "400">
		<rect x="20", y="0", width="40", height="40", fill="steelblue"></rect>
		<rect x="20", y="45", width="140", height="40", fill="steelblue"></rect>
		<rect x="20", y="90", width="240", height="40", fill="steelblue"></rect>
		<rect x="20", y="135", width="340", height="40", fill="steelblue"></rect>
		<rect x="20", y="180", width="800", height="40", fill="steelblue"></rect>
	</svg>
  </body>
</html>
```

마지막 다섯번째 사각형은 width를 800이나 줬지만 SVG의 너비가 400 이기 때문에 그 이상은 출력되지 않는다

-----------------------------------

# 위에서 했던 내용을 D3의 구문으로 변경하기

`<svg></svg>` 부분을 모두 지우고 (body안에 있는 내용 전부 지우기)

크롬 개발자도구 콘솔창에서 타이핑한다

D3가 제대로 불러졌는지 꼭 확인

콘솔창에서 다음과 같이 타이핑

```javascript
d3.select("body").append("svg").attr("width",400).attr("height",400);

d3.select("svg").append("rect").attr("width",40).attr("height",40).attr("fill","steelblue");
```

D3 select문은 html/css에서 해당하는 첫번째 요소를 잡아서 반환한다

select("body")에서 body항목을 잡아서 하위에 svg라는 항목을 만들고 너비는 400, 높이는 400으로 하겠다. 의 의미

select("svg")면 svg항목을 잡아서 하위에 rect라는 항목을 만들고, 너비 40, 높이 40, 배경색은 steelblue로 지정하겠다

콘솔창에서 할 수도 있고 html 문서안에 자바스크립트 구간을 만들수도 있고 

자바스크립트는 다른 파일에 저장한 다음에 따로 불러올 수도 있다.

코드가 길어지면 따로 관리하는 것이 편하다

자바스크립트/html/css를 분리하면 에디터에서 편집하기 좋다 각각의 문법에 맞는 하이라이트를 적용할 수 있음

```html
<!DOCTYPE html>
<html>
  <head>
    <title>D3 first tutorial</title>
    <script type="text/javascript" src="d3.min.js"></script>
  </head>
  <body>
	<script>
		d3.select("body").append("svg").attr("width",400).attr("height",400);

		d3.select("svg").append("rect").attr("width",40).attr("height",40).attr("fill","steelblue");
	</script>
  </body>
</html>
```

`<script></script>` 안에 d3로 작성한 결과. 결과물은 같다

select로 선택하거나 append로 생성해낸 객체의 경우

변수로 저장하면 해당 선택을 재사용 하는 것이 가능하다

script 내부만 변경해보면

```javascript
var svg = d3.select("body")
			.append("svg")
			.attr("width",400)
			.attr("height",400);

	svg.append("rect")
		.attr("width",40)
		.attr("height",40)
		.attr("fill","steelblue");
```

위 코드를 살펴보면 "body" 내부에 400x400의 svg를 생성하고

생성한 svg를 다시 선택하여 그 아래에 40x40의 사각형을 만들었다

바로 위에 있던 코드와 내용은 동일하다

이후에는 script 항목 안에 있는 내용만 변경하는 방식으로 진행하겠다

또는 크롬 콘솔창에서 타이핑

```javascript
		var svg = d3.select("body")
					.append("svg")
					.attr("width",400)
					.attr("height",400);

		svg.append("rect")
			.attr("x", 10)
			.attr("y", 10)
			.attr("width",40)
			.attr("height",20)
			.attr("fill","steelblue");
		svg.append("rect")
			.attr("x", 10)
			.attr("y", 31)
			.attr("width",100)
			.attr("height",20)
			.attr("fill","steelblue");
		svg.append("rect")
			.attr("x", 10)
			.attr("y", 52)
			.attr("width",80)
			.attr("height",20)
			.attr("fill","steelblue");
		svg.append("rect")
			.attr("x", 10)
			.attr("y", 73)
			.attr("width",140)
			.attr("height",20)
			.attr("fill","steelblue");
```

400X400 SVG에 수작업으로 막대 네개를 만들었다

Elements 창에 어떻게 적용되는지 확인하면서 진행하자


언제까지고 수작업으로 할수는 없는법 간단한 수치를 도형에 연결해보자

```javascript
  var svg = d3.select("body")
				.append("svg")
				.attr("width",400)
				.attr("height",400);
	var data = [40, 100, 80, 140, 60, 70];
	
	svg.selectAll("rect")
		.data(data)
		.enter()
		.append("rect")
		.attr("x",10)
		.attr("y", function(d, i){return i * (20 + 1) })
		.attr("width",function(d){return d})
		.attr("height", 20)
		.attr("fill", "steelblue");
```

data라는 변수를 만들어서 막대의 너비에 반영할 수치를 작성했다

svg에서 rect라는 요소를 전부 선택하도록 했다

하지만 현재 svg에는 아무것도 없는 상태

선택해서 뭔가 잡히면 그 하위항목으로 들어간다

`data()` 함수를 통해 요소와 연결시킬 데이터를 지정하고

`enter()`를 사용하면 연결시킨다

svg안에 rect 항목이 아무것도 없었는데 들어온 데이터가 6개니

일단 6개의 항목을 D3가 준비한다

그리고 append를 사용하면 해당 요소가 데이터의 개수만큼(여기선 6개) 생김

그 뒤에는 똑같이 구성 요소들을 적어주면 되는데

`function(d, i){return d}` 를 보면 d는 data의 값이고 i는 인덱스(순서) 이다

i는 0부터 시작

그러니 y축 값은 각 항목들이 20 + 1 만큼 떨어지게 되는거고

막대의 너비에는 data의 값들이 들어간다